language: r
cache:
  packages: true
  directories:
  - _book
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libxml2-dev
branches:
  only:
  - main
script:
- make all 
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIBW6BTQUUTKCF5YA
  secret_access_key: $S3_SECRET
  bucket: cookbook.carpentries.org
  local-dir: _book
  acl: public_read
