## Introduction

Welcome to the Carpentries' Community Cookbook!

The aim of this guide is to provide a place to gather together background, and personal stories about a range of community building tools and practices that are useful in creating peer learning communities in academic an research environments. Through this guide we hope to collect 'recipes' or practical tips and tricks to aid you in creating your own strong, local communities based on the local 'ingredients' you have on hand. Every campus and organization will be a bit different, so there is no single right way to create a local community. However, the ideas gathered here seek to provide ideas for you to try, knowing that these have been tested by others. Please don't see this guide as prescriptive of the exact steps that will work for you, but as an inventory of possibilities you can experiement with to make your own community unique. Come join us at our [quarterly Champions calls](http://pad.software-carpentry.org/champions), where we share ideas and support those trying to build their own local research computing communities of practice.

## Building or improving your own local community

Investing your time in developing a communtiy of practice around the computational skills is an activity that can help you and others in developing their research tools and skills. There is such a rapid pace of innovation and development in computational tools, it can seem daunting and impossible to get started. At the same time, the rate at which we can collect research data sets is growing beyond our mental models for imagining how we'll process all that data. The role of community in developing skills and infrastructure is incredibly important, and the ability of groups of people sharing ideas and tools with each other can accelerate and improve your capabilities and research outcomes. 

The Carpentries have found that developing local communities takes intentional and committed boots-on-the-ground community champions who are energetic, innovative and excited to support and grow community. Over the past few years we as a broader global community have gathered together the lessons learned and shared across the world and we're sharing them here through this coookbook. We hope that you can learn from, be inspired by and contribute back to this cookbook all the recipies and ideas you've tried. Join our quarterly meetings and get support from our global community, or give support to others that are just getting started. 

## What is a community of practice?

A community of practice is simply a group of people who share a particular craft or shared purpose with each other. In the case of The Carpentries communities, this tends to be communities around computational skills applied toward research challenges. How exactly this looks at your organization or institution is up to you. Some communities support bioinformaticians in their efforts to wrangle and improve bioinformatics workflows. Others cast wide nets with terms like "Digital Scholarship" to invite and include those from all disciplines and backgrounds to come together for support around computational skills. Still others run small very focused study groups or book clubs on niche topics, working to support each other as they develop new skills. How or what you develop is up to you, you'll probably find that you already have some communities of practice you participate in. Whether it is your lab group, the team you work for, or a cross-institutional collaboration you're a part of, these are all communities of practice. This guide will give you some ideas and tips for how to build and interconnect these existing communities, or build new ones that have share goals and purpose.

## Contributing

we invite you to contribute to this guide and hope for it to be a living and growing document of curated ideas. In this cookbook we look to gather from our global community the practices they use to initiate and cultivate these communities. If you have a particular practice that has worked for you, we invite you to contribute it to our community. Please open an [issue](https://github.com/carpentries/community-cookbook/issues) and share a link or resource, or  if you're familiar with Git, a [pull request](https://github.com/carpentries/community-cookbook/pulls) with a suggested addition and our cookbook maintainers will work with you to integrate the contribution.

## Codes of Conduct

The Carpentries community strongly encourages a Code of Conduct (CoC) being in place at all gathering places, online and offline. CoCs support open and collaborative environments and ensure there are stated rules for appropriate and inapropriate behavior. We encourage you to adopt/develop a CoC for any activities you plan and to notify your attendees/participants of the text and that they are expected to abide by. There are many great CoCs out there, and it is really up to you to select one that you feel fits the needs of your activities and community. For certain events, such as Carpentries workshops, you will be required to adopt [the Carpentries CoC](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) to run the event under their name.