applicable# Skills Workshops

Short format workshops that run over one or more days can be a great way to
bring people together to share skills. For workshops to be most impactful, it is
important to use good quality lessons and have them taught by prepared
instructors. The Carpentries supports and mentors a global community of
instructors and lessons they can teach.  

# The Carpentries

The Carpentries is an umbrella organisation which sits over the top of several
lesson communities in order to provide a common super-structure which focuses on
valuing teaching skill and quality lessons to bring workshops with greater
impact to research organisations. A major activity of the organisation is to
run  instructor training workshops which prepare instructors drawn from research
and research support communities to use evidence based teaching practices. The
[Instructor Training
Program](https://carpentries.github.io/instructor-training) is openly and
freely made available under a Creative Commons CC-BY license model. The
Carpentries also runs instructor training events for
[member organisations](https://carpentries.org/members/) who
make a commitment to annually supporting them. Through trained instructors and
openly developed community lessons, any research organisation in the world can
create a highly effective and impactful instructor community. To learn more,
you can look at the [membership models](https://carpentries.org/membership/)
and reach out to
[memberships@carpentries.org](mailto:memberships@carpentries.org) for more
information.

## Software Carpentry

Overview of [Software Carpentry](https://software-carpentry.org/) workshops

### Lessons

Software Carpentry aims to help people begin to think computationally about the
work they do. It does this by introducing pieces of software which are useful
stable and used by very large communities of researchers around the world. The
emphasis isn't on new and flashy technologies, but those that have been
battle-tested and used for years. Software Carpentry starts with  the shell for
task automation, then by introducing a programming language such as R or Python,
and then by bringing in version control systems such as Git to ensure that
research work done can be easily retrieved, repeated, or adapted for other uses.
Using these methods, learners can lay the foundation for performing open,
reproducible research.

Software Carpentry maintains lessons in the Unix Shell, Git, R, Python, SQL,
Make and Mercurial. Software Carpentry lessons focus on teaching tools in a
discipline-agnostic way, in order to help researchers from all disciplines
develop skill with the tools. Software Carpentry lessons aren't meant to be
exhaustive and comprehensive enumerations of all possible features of a
particular tool. Instead the lessons seek to strike a balance of reducing
cognitive load, while empowering the researcher to have a better understanding
of how the tool could be applied in their workflow.

Visit the [Software Carpentry Lessons
website](https://software-carpentry.org/lessons/) to see the most up to date
listing of our lesson

#### Command Line

Command Line Interfaces or (CLIs) are a time-tested and efficient way to direct
and control a computer. Software Carpentries' flagship UNIX Shell lesson is the
most taught lesson in Software Carpentry and helps bring novice learners toward
an appreciation of their benefit. We teach a very small number of tools, but
work through live coding and challenges we break down and demystify the dark art
of constructing command line incantations. At the end of this module, learners
have a better sense of using the shell environment to glue together programs and
code from various languages. They also learn how to write simple scripts which
are generalized and abstracted to run over different kinds of input such as
piped text or directories of files.

#### Version Control

The Software Carpentry version control lessons help to motivate version control
in a research context. They focus on the mechanics of how the version control
tool works, and then how to use the tool in an online and then collaborative
context. In this way we build up a mental model for the power of version control
and demonstrate through challenges and activities ways the learner can leverage
version control in their own research workflows.

#### Programming

The programming lessons in Software Carpentry focus on a particular scientific
programming language, R, Python or MATLAB and help learners feel more
comfortable in that language while gaining exposure to important software
development practices. The Software Carpentry approach is one of empowering
learners, so rather than teaching an exhaustive set of data types, the lessons
focus on practical examples. Learners then learn about new data types and
language constructs along the way, preventing data types being taught in the
abstract.


The Carpentries can help you to run your first Software Carpentry Workshop at
your organisation.
[Request a workshop](https://amy.carpentries.org/forms/workshop/)
today!


## Data Carpentry

A [Data Carpentry](https://datacarpentry.org/workshops/) workshop teaches the
core skills for working with data effectively and reproducibly.

When working with data, it’s often difficult to figure out what skills to learn
or how to get started learning them. In Data Carpentry, we identify the
fundamental skills needed in a given domain and develop and teach these skills
in hands-on, two-day, interactive workshops. Workshops are currently designed
for people with little to no prior computational experience and are
domain-specific, so that researchers are working with data most relevant to
their own work. They follow a narrative structure, working with one dataset
through the whole data lifecycle from data and project organization to data
analysis and visualization.

### Lessons

Data Carpentry currently have [curriculum](https://datacarpentry.org/lessons/)
in:

- Ecology Genomics Geospatial data Social sciences

The Carpentries can help you to run your first Data Carpentry Workshop at
your organisation.
[Request a workshop](https://amy.carpentries.org/forms/workshop/)
today!


## Library Carpentry

[Library Carpentry](https://librarycarpentry.org/) aims to help people in
library and information roles develop software and data skills.

### Lessons

Library Carpentry has nine [lessons](https://librarycarpentry.org/#portfolio) in
the works, some more mature than others. New lessons are being drafted around
FAIR principles and digital preservation.

| Lesson | Scope |
| :----- | :----- |
|Data intro for librarians | An introduction to data structures, regular expressions, and computing terms |
|Unix Shell| An introduction to command line interfaces and task automation using the Unix shell |
| OpenRefine | An introduction to cleaning up and enhancing a dataset using OpenRefine |
| Git Intro for Librarians | An introduction to version control using Git and GitHub for collaboration |
| SQL for Librarians| An introduction to relational database management using the SQLite tool |
| Webscraping | An introduction to extracting structured data from websites using a range of tools |
| Tidy data for librarians | An introduction to good data organisation, which is the foundation of much of our day-to-day work in libraries |
| Introduction to Python | An introduction to Python, a general purpose programming language |
| Data Intro for Archivists | An introduction to data structures, regular expressions, and computing terms for archivists |

The Carpentries can help you to run your first Library Carpentry Workshop at
your organisation.
[Request a workshop](https://amy.carpentries.org/forms/workshop/)
today!

## Other Skills Workshops

The [Programming Historian](https://programminghistorian.org) has a number of
useful [lessons](https://programminghistorian.org/lessons/) on a range of tools
and skills.

These lessons would be applicable to anyone who wants to improve their digital
skills - they have wider relevance beyond the fields of history and the
humanities.

# Help Sessions

Help sessions of many kinds have been created within Carpentries member
institutions. What is common is that such sessions be  regularly scheduled and
frequent, and provide a neutral space where people can come together to support
each other with technical challenges.

Events of this type include Hacky Hour, PhTea, Code and Pizza, SkillShares, or
Office Hours. These kinds of events can be slow to get started, with it
sometimes taking weeks or months to develop a steady cohort of regulars. To get
started, think about assembling an 'anchoring' group that can offer a range of
useful skills. These might be sysadmins, bioinformaticians, a GIS librarian, a
person with data management knowledge, HPC or other technical support staff, and
graduate students from a range of disciplines. If this seems completely
unattainable, start out with small. Hacky Hours have been started by two people
and have then seen them grow. The key is to start, and not to get discouraged if
people don't flock in for advice at first. Word of mouth will help populate it
as time goes by.

Mature community help sessions become as useful to the so-called experts as they
are for the novice and intermediate researchers. Having them in an informal
setting with the ability to order food/coffee/beer at your own expense is also
popular. In other cases, a budget for pizza and/or snacks is requested to
provide extra enticement.

## Hacky Hour

Hacky Hours are informal, regularly scheduled meetups where researchers can
bring research IT-related issues for discussion or help.

These might include issues with Python, R, HPC, statistics, MatLab or other
software.

They are generally volunteer-run, and aim to build referral networks and
communities of practice around research software and skills.

### Starting a Hacky Hour

#### Finding a location

A cafe or restaurant on or near campus is a nice informal location. Take over a
large table and put up a sign to try and attract people in and make sure they
find you. Sometimes it's obvious which group is the hacky hour, they all have
laptops out!

If a cafe isn’t available somewhere that people can bring food to is a good
alternative. Having free food available is always a good way to attract people.
If this isn’t possible then booking a room at lunch time and suggesting people
bring their lunch can work instead.

Traditional lecture theatres should be avoided as it's not the best type of room
to have lots of small discussions in. A room with several smaller round tables
works best.

#### Choosing a Time

It can be difficult to find a time that fits for everyone. It might be a good
idea to try out different times or to alternate between different time slots.
Try to find a slot that doesn’t clash with major meetings or seminars amongst
groups who are likely to come. You might not initially know when all these are
but will find that people will start to say they’d like to come but can’t make
it due to a clash. If you’re using a cafe, try to find a quiet time when there
will be space and not too much background noise.

#### Promoting a Hacky Hour

* Put up posters and flyers in places where researchers might see them. For
* example in/near research student offices. Send emails to mailing lists of
* people who might be interested. For example research students, research staff
* and HPC users. Get it added to your university’s events calendar or sent onto
* events mailing lists. Mention them in Software Carpentry workshops or any
* other relevant presentations. Tell anyone you know who’s looking for help that
* it’s a good time to ask. Tell anyone you know who might offer help that it’s a
* good time to offer it. If providing this kind of support isn’t really their
* job it can be a good way of restricting it to just an hour a week.

#### Some Hacky Hour resources

- [Hacky Hour Handbook](https://github.com/amandamiotto/HackyHourHandbook)

##### Hacky Hour groups around the world

Australia:

* The University of Queensland - UQ Hacky Hour [Twitter](https://twitter.com/hackyhourstluc) and [website](https://hackyhourstluc.wordpress.com/)
* Griffith Hacky Hour [Twitter](https://twitter.com/hackyhourgu) and [website](https://hackyhourgriffith.wordpress.com/)
* Curtin University Hacky Hour [Twitter](https://twitter.com/CUHackyHour)
* University of Western Australia - UWA Hacky Hour [Twitter](https://twitter.com/HackyHourUWA)
* James Cook University - JCU Hacky Hour [Twitter](https://twitter.com/JCUHackyHour)
* Queensland University of Technology - QUT  Hacky Hour [Twitter](https://twitter.com/GPHackyHour)
* Murdoch University Hacky Hour [Twitter](https://twitter.com/HackyH_Murdoch)

New Zealand:

* [Uni of Auckland Hacky Hour](https://twitter.com/uoahackyhour)

UK

* Aberystwyth University [website](https://tinyurl.com/HackyHourAber),
* [facebook](https://www.facebook.com/hackyhouraber/) and
* [twitter](https://twitter.com/hackyhouraber).

Germany

* [Göttingen](https://hackyhour.github.io/Goettingen/)
* [Würzburg](https://hackyhour.github.io/Wuerzburg/)
* [Cologne](https://hackyhour.github.io/Cologne/)

USA

* [Pennsylvania State](http://www.hackyhour.com)

# Carpentries Study Groups

## What are they?

The Carpentries study group is a small group of people who regularly meet to
discuss shared fields of study. These could be the use of programming languages
like R, Python or statistics in research. These groups can be found in various
institutions, and different settings that share common interest. They meet up
twice a month on average or as often as needed.

They share S.M.A.R.T goals within the set curriculum even broader, to widen the
scope of what is already known however contributing to the body of knowledge.
Study groups are meant to share and solve problems together, it may not
necessarily be from grassroots up or top-down but they share skills and
expertise on the subject in question. It is where certain advancements are done,
corrections are made or other alternative ways to solve problems are discussed
and positively critiqued at the same time building one another’s capabilities
and knowledge to grow.

Each study group is unique and draws on the backgrounds and abilities of its
members to determine the material that will be covered. Study groups have helped
many individuals especially novices who have trouble being in a large group
setting to be able to be at an advancement close to competent and even more
often, a leader who is not actively studying the material will direct group
activities. Some institutions actively set up study group programs for students
to sign up. The carpentry study groups include 3-5 students and  an instructor
who has the specific skill(s) needed for that group- moreover drawn from the
curriculum. Study groups help build individuals’  where a big group cannot
reach.

## How to start one?

What are the steps to bring a study group to your own institution?

## Advice and peer support

Outline the periodic study group international meetings and how study groups
support each other.

## See if there are Study Groups near you

FIXME - link to Study Group website/map

# Book Clubs

See [Katherine Wu's "Continuing Education at Work"
talk](https://www.youtube.com/watch?v=9uRho69xSAI&t=165).

# Events

There are various kinds of annual/semi-annual events you can run to give your
community a focused opportunity to share and plan more intensely with each
other, and to invite new members into the community. Within The Carpentries
campus communities, ResBaz (Research Bazaar) is a popular multi-day event to
share research software tools and how to use them. These events are as much
about training and skills as they are about networking and ideas. There are many
types of un-conference and satellite conference that can be exciting to bring to
your organization. These include events like OpenCon-local, THATCamp and more.
Planning one of these local satellite events can be a great way to bring people
together on your campus. Additionally, there are several events in the
Carpentries community that draw Carpentries instructors. We have an etherpad
where we share among the instructor community what conferences we'll be
attending. In the cookbook we'll list some marquee events that bring many
Carpentries community members together.

# Research Bazaar (ResBaz)

ResBaz is a 3-day research festival to teach skills and help people build local
communities. It generally encompasses workshops such as Software and Data
Carpentry workshops, along with a range of talks, games, poster and networking
sessions such as the Knowledge Bazaar.

ResBaz was first run in Melbourne in 2015. The model quickly became popular, and
ResBaz events were run in ten cities worldwide in 2016 and in 14 locations in
2017. [ResBaz 2018](https://resbaz.github.io/resbaz2018/) events have been run
in nine cities this year.

## ResBaz resources

- [ResBaz blog](https://resbazblog.wordpress.com/author/resbaz/) and [ResBaz on
  Twitter](https://twitter.com/resbaz) - the blog is the main source of
  information and links, including a FAQ, while the Twitter feed will list news
  and announcements [ResBaz Cookbook
  latest](https://www.gitbook.com/book/heydejan/resbaz-cookbook/details)  and
  [Older ResBaz cookbook](https://github.com/resbaz/cookbook/wiki) [ResBaz slack
  channel](https://resbaz-team.slack.com/?redir=%2Fmessages%2Fgeneral) - monthly
  catch up [Images from 2017 ResBaz in
  Brisbane](https://www.flickr.com/photos/100739735@N06/with/32743902091/)
  -includes shots of workshops, stalls, sponsors etc [ResBaz
  Arizona](https://twitter.com/resbazaz) - AZ also run HackyHour and PhTea
  sessions

# CarpentryCon

CarpentryCon is the key community building and networking event in the
Carpentries' annual calendar.

The inaugural 2018 [CarpentryCon](http://www.carpentrycon.org/) was held from 30
May - 1 June at University College, Dublin.

The theme of CarpentryCon 2018 was *Building Locally, Connecting Globally*.

- [Summary of event](https://carpentries.org/blog/2018/06/carpentry-con-report/)
  by Belinda Weaver. Thoughts on community after
  CarpentryCon](https://carpentries.org/blog/2018/06/value-of-community/) by
  Toby Hodges. [African Task Force response to
  CarpentryCon](https://carpentries.org/blog/2018/07/actf-carpcon-post/)
  [Carpentries in Latin America response to
  CarpentryCon](https://carpentries.org/blog/2018/07/carpentrycon-la/)
  [CarpentryCon photo
  stream](https://www.flickr.com/photos/134305289@N03/sets/72157667641880727)by
  Bérénice Batut [Tweets from
  CarpentryCon](https://carpentries.org/2018/06/carpentrycon-tweets) - a summary
  provided by Francois Michonneau

## Purpose and Scope of CarpentryCon

- **Community Building:** bring together members of the Carpentry community,
  including instructors, partners, advocates, and staff, together with people
  sharing similar interests from around the globe. We had a “come and learn”
  format that is different from most conferences.
- **Sharing Knowledge:** The
  event included sessions on teaching methods, curriculum development, community
  organization, and leadership skills.
- **Networking:** Opportunities were
  provided for participants to come together informally to share stories about
  challenges and successes.
- **Contributed talks/posters:** There was a poster
  session where attendees shared how they have incorporated Carpentry techniques
  into their own research and teaching, and/or how they have grown their local
  Carpentry community. This was crucial as presenting was a requirement for
  attendees who sought travel support from their home institution.

## The CarpentryCon Task Force

The [CarpentryCon Task
Force](https://github.com/swcarpentry/board/tree/master/TaskForces/2018-CarpentryCon)
was created within the Carpentries to help organize and coordinate CarpentryCon
events.

All progress on above items is reported within the [CarpentryCon
repo](https://github.com/carpentries/carpentrycon).

## Useful Links

[meetings](http://pad.software-carpentry.org/2018carpentrycontaskforce)
[minutes](https://github.com/carpentries/carpentrycon/tree/master/Minutes)

# SatRdays

[SatRdays](https://satrdays.org/) are
[SQLSaturday](https://sqlsaturday.com/default.aspx)-inspired, community-led,
one-day, regional and very affordable conferences around the world to support
collaboration, networking and innovation within the R community.

# THATCamp

> The Humanities and Technology Camp, is an open, inexpensive meeting where
> humanists and technologists of all skill levels learn and build together in
> sessions proposed on the spot

THATCamp is an open unconference model for bringing a skills meetup to your
university or organization. Being an unconference it is highly flexible and up
to you and your organizing committee to make it work. It is a popular model in
academic libraries and digital humanities centres around the world.

More information can be found at: http://thatcamp.org/

# International Events

## Pycon

Pycon is the flagship conference among the Python Community worldwide. There are
a series of other satellite and regional Pycons, but nothing quite compares to
the flagship event. The Python community is an incredible example of an open and
inclusive community which invites contribution from all walks of life. If you're
a Python developer or aspiring Python developer, there is a good chance you'll
find long time friends and a support community by attending this conference. It
is gotten big over the years, but the selectivity of talks has kept the quality
incredibly high. If you have a chance, and are into Python, check it out! You'll
learn many things you can bring back both how the organization runs, and about
Python.

## SciPy

Scipy is a conference for the Python community which focuses specifically on
scientific Python and the major libraries underpinning scientific Python. This
includes things like scipy, numpy, matplotlib, scikit-learn and other
foundational tools and libraries. Researchers of all walks, from academia to the
private sector come together each year in Austin Texas to share and build
community. The SciPy community is not quite as diverse as the broader Pycon
community, but it has been working hard over the years to broaden participation
in the event. Usually held in Austin, Texas this event is a great meeting of the
minds for those involved in scientific Python.

## RStudio Conference

## SC - the Supercomputing conference

## International Data Week

# Vendor Training

If you have researchers who use a particular vendor tool, sensor or apparatus,
it is often possible to bring that vendor in for local on-site training.
Depending on the vendor, this can be a costly per-seat workshop, or it can be
done for free. It is also possible to work to build a relationship with the
vendor so that theyy are able to see how their training might lead to future
sales or to a continued use of their products. In this section, we'll share some
thoughts and ideas on vendor supplied trainings that can be useful to build into
your local community. Vendors are working to stay in business, and your ability
as a researcher to use their complex tools and systems is an important part of
how you're able to be research-capable. By working together to seek high-quality
and relevant training from the key vendors supporting academic research, we can
work together to make these trainings impactful and useful for our local
communities.
