# Communities need useful tools to help them organise and connect. We list a few here that might be of use.

## Websites

Generating your own website for your local community can be a great way to drum up participation and enthusiasm for your group, and to help with organisation of meetings. A free tool like GitHub Pages can allow you to quickly and easily create static-content websites which share important information about your community. There is a great guide for [Getting Started with GitHub Pages](https://pages.github.com/) that can help you get going. In short, GitHub pages is free web hosting that can allow you to share with the world the work of your group and share it with the world. The collaboration model of Git and GitHub using pull-requests also allows you to distribute the load and responsibility of website maintenance and updating across your local group. On top of that, you'll all be working in and enhancing your skills around Git/GitHub collaboration models as you do!

## Git/GitHub

* GitHub Organisation
* Repo for Meeting Minutes
FIXME

## Calendar

Google Calendars built into web pages
FIXME

## Event registration

* [Eventbrite](https://eventbrite.com) allows you to organise both free and paid events - they handle logistics such as ticketing, and waitlists. They take a small fee for paid events but there is no charge for use of the free event service.
* university's questionnaire form system for registrations/surveys

## Mailing Lists

Mailing lists can be a great way to keep a growing community connected to each other. Having a focused charter for each list can be helpful to reign in discussions as well. As lists grow, and draw larger participation it can be important to develop a moderator team that is able to tend to moderator requests and keep the list conversations productive and civil.

* **University lists** - Many universities and organizations run a campus-wide listserver where university members can create lists for open subscription.
* **Mailman** - The open source tool [Mailman](http://www.list.org/) can be installed on a server and be used to run your own list infrastructure. This is recommended only if you have some system administration experience as it is a fairly advanced undertaking.
* **TopicBox** - TopicBox is a premium/paid mailing list platform which delivers a high-quality user web interface. To see TopicBox in action, check out [The Carpentries Mailing Lists](https://lists.carpentries.org)
* **Google Groups** - Google groups are a free option which also allows for a publicly available archive of the messages to the group.

## Newsletters

Staying in contact with your growing community can be done with email lists, or sometimes it is useful to have a broadcast announcement or newsletter list. This can be done manually by handling a list of email addresses on your own, but there are mailing list services that make it really easy and free for small lists. As your community grows you can segment your list into particular interest areas and engage with community members based on their expressed interest areas. This can make appeals for participation or volunteering very effective, as you're only contacting those who have already expressed interest in that area of participation/contribution.

* MailChimp - free and powerful for small groups
* Constant Contact - pricing starts at $20/month
* TinyLetter - by MailChimp but allows you to send a simple periodic newsletter

## Instant Messaging/Chat

* [Gitter](https://gitter.im/) - Free and open
* [RocketChat](https://rocket.chat/) - Free when self-hosted
* [Slack](https://slack.com) - Free for limited history/archive.

## Shared Documents

Shared documents can really enable collaborative and participatory engagement opportunities across your community. Using video and audio conferencing tools in conjunction with a shared document is very effective. A log of discussions can be recorded for the benefit of both the participants and those who may not have been able to attend. Group involvement such as voting on topics and ideas, or response to question prompts can be pre-loaded in the shared document. Additionally shared documents can be used as wiki-like locations to record important information. In The Carpentries community has a [pad of pads](http://pad.carpentries.org/pad-of-pads) showing many examples of how shared documents can be leveraged. They're used for periodic meetings, sign-ups to discussion sessions, sharing conference attendence and more. These create a powerful shared purpose and encourage engagement in what can otherwise be unengaging video/audio calls.

* Google docs - Great shared document platform, somewhat required users to have a Google account.
* Etherpads - Open source, requires hosting on your own infrastructure.
* [HackMD](https://hackmd.io/) - An alternative to Etherpads that is growing in popularity. Allows collaborative notetaking with Markdown.

## Video Conferencing
* [Google Hangouts](https://hangouts.google.com/) - Free
* Zoom - Paid
* [Jitsi Meet](https://jitsi.org/jitsi-meet/) - Free
